# Generated by Django 3.1.1 on 2020-09-17 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='XApiConversion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameModel(
            old_name='SlackEvent',
            new_name='RawSlackEvent',
        ),
    ]
