# Generated by Django 3.1.1 on 2020-09-17 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0002_auto_20200917_2212'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlackEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
