# Generated by Django 3.1.1 on 2020-09-18 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0004_auto_20200917_2311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slackevent',
            old_name='payload',
            new_name='_payload',
        ),
        migrations.AddField(
            model_name='slackevent',
            name='api_type',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='slackevent',
            name='channel_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
