# Generated by Django 3.1.1 on 2020-09-18 23:12

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0005_auto_20200918_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='slackevent',
            name='mentioned_users',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
