# Generated by Django 3.1.1 on 2020-09-20 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0007_delete_xapiconversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='slackevent',
            name='has_mentions',
            field=models.BooleanField(default=False),
        ),
    ]
