# Generated by Django 3.1.1 on 2020-09-21 22:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SlackField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slack_field_type', models.CharField(choices=[('verb', 'Verb'), ('object', 'Object')], max_length=255)),
                ('slack_event_field', models.CharField(max_length=255)),
                ('expected_value', models.CharField(help_text='Enter `None` if the expected value is supposed to be empty', max_length=255)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='XApiVerb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('iri', models.CharField(help_text='Enter either verb IRI', max_length=1048)),
                ('display_name', models.CharField(max_length=255)),
                ('language', models.CharField(choices=[('en-US', 'US English'), ('en-UK', 'UK English'), ('it', 'Italian'), ('es', 'Spanish'), ('de', 'German')], max_length=5)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='XApiObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('iri', models.CharField(help_text='Enter the Activity IRI.', max_length=1048)),
                ('display_name', models.CharField(max_length=255)),
                ('language', models.CharField(choices=[('en-US', 'US English'), ('en-UK', 'UK English'), ('it', 'Italian'), ('es', 'Spanish'), ('de', 'German')], max_length=5)),
                ('description', models.TextField(blank=True, null=True)),
                ('activity_type', models.CharField(blank=True, help_text='Enter an Activity Type IRI if applicable. See some examples at https://registry.tincanapi.com/#home/activityTypes', max_length=1048, null=True)),
                ('more_info', models.CharField(blank=True, help_text='Enter an IRI for more info.', max_length=1048, null=True)),
                ('object_type', models.CharField(choices=[('Activity', 'Activity'), ('Agent', 'Agent'), ('Group', 'Group'), ('Statement Reference', 'Statement Reference'), ('SubStatement', 'SubStatement')], max_length=255)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Activities',
            },
        ),
        migrations.CreateModel(
            name='XApiActor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('iri', models.CharField(help_text='Enter either email address, SHA1 of an email address or anOpenID uri.', max_length=1048)),
                ('iri_type', models.CharField(choices=[('mbox', 'Email Address'), ('mbox_sha1sum', 'Email SHA1'), ('openid', 'OpenID')], max_length=255)),
                ('slack_user_id', models.CharField(max_length=255)),
                ('display_name', models.CharField(max_length=255)),
                ('object_type', models.CharField(choices=[('Agent', 'Agent'), ('Group', 'Group')], max_length=255)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SlackVerbField',
            fields=[
                ('slackfield_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='xapi.slackfield')),
                ('xapi_verb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slack_field_connector', to='xapi.xapiverb')),
            ],
            bases=('xapi.slackfield',),
        ),
        migrations.CreateModel(
            name='SlackObjectField',
            fields=[
                ('slackfield_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='xapi.slackfield')),
                ('xapi_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slack_field_connector', to='xapi.xapiobject')),
            ],
            bases=('xapi.slackfield',),
        ),
    ]
