# Generated by Django 3.1.1 on 2020-09-20 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='object_type',
            field=models.CharField(choices=[('Agent', 'Agent'), ('Group', 'Group')], default='Agent', max_length=255),
            preserve_default=False,
        ),
    ]
