# Generated by Django 3.1.1 on 2020-09-21 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slackobjectfield',
            options={'verbose_name': 'Slack-Object Field', 'verbose_name_plural': 'Slack-Object Fields'},
        ),
        migrations.AlterModelOptions(
            name='slackverbfield',
            options={'verbose_name': 'Slack-Verb Field', 'verbose_name_plural': 'Slack-Verb Fields'},
        ),
        migrations.AlterModelOptions(
            name='xapiactor',
            options={'verbose_name': 'XApi Actor', 'verbose_name_plural': 'XApi Actors'},
        ),
        migrations.AlterModelOptions(
            name='xapiobject',
            options={'verbose_name': 'XApi Object', 'verbose_name_plural': 'XApi Objects'},
        ),
        migrations.AlterModelOptions(
            name='xapiverb',
            options={'verbose_name': 'XApi Verb', 'verbose_name_plural': 'XApi Verbs'},
        ),
    ]
