# Generated by Django 3.1.1 on 2020-09-20 21:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('xapi', '0003_slackconnectorfield_slackverbconnector_verb'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlackField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slack_event_field', models.CharField(max_length=255)),
                ('expected_value', models.CharField(help_text='Enter `None` if the expected value is supposed to be empty', max_length=255)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('verb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slack_connector_fields', to='xapi.verb')),
            ],
        ),
        migrations.RemoveField(
            model_name='slackverbconnector',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='slackverbconnector',
            name='verb',
        ),
        migrations.DeleteModel(
            name='SlackConnectorField',
        ),
        migrations.DeleteModel(
            name='SlackVerbConnector',
        ),
    ]
