# Generated by Django 3.1.1 on 2020-09-21 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xapi', '0003_auto_20200921_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xapiactor',
            name='object_type',
            field=models.CharField(choices=[('Agent', 'Agent'), ('Group', 'Group')], default='Agent', max_length=255),
        ),
    ]
