# Generated by Django 3.1.1 on 2020-09-24 21:02

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('xapi', '0004_auto_20200921_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='xapiobject',
            name='extensions',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
