# Generated by Django 3.1.1 on 2020-09-21 21:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('xapi', '0004_auto_20200920_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='object_type',
            field=models.CharField(choices=[('Activity', 'Activity'), ('Agent', 'Agent'), ('Group', 'Group'), ('Statement Reference', 'Statement Reference'), ('SubStatement', 'SubStatement')], max_length=255),
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('iri', models.CharField(help_text='Enter the Activity IRI.', max_length=1048)),
                ('display_name', models.CharField(max_length=255)),
                ('language', models.CharField(choices=[('en-US', 'US English'), ('en-UK', 'UK English'), ('it', 'Italian'), ('es', 'Spanish'), ('de', 'German')], max_length=5)),
                ('description', models.TextField(blank=True, null=True)),
                ('activity_type', models.CharField(help_text='Enter an Activity Type IRI if applicable. See some examples at https://registry.tincanapi.com/#home/activityTypes', max_length=1048)),
                ('more_info', models.CharField(help_text='Enter an IRI for more info.', max_length=1048)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
