# Generated by Django 3.1.1 on 2020-10-01 22:26

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('xapi', '0005_xapiobject_extensions'),
    ]

    operations = [
        migrations.CreateModel(
            name='LrsConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lrs_endpoint', models.CharField(max_length=255, unique=True)),
                ('lrs_auth_user', models.CharField(max_length=255)),
                ('lrs_auth_pw', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='xapiobject',
            name='extensions',
            field=jsonfield.fields.JSONField(blank=True, help_text='Needs to be a valid list with the Slack Event attributes to be added to the Extensions (e.g. ["message_text", "event_id"]. The available Extensions can be configured in xapi/models.py', null=True),
        ),
    ]
