# Generated by Django 3.1.1 on 2020-09-21 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xapi', '0005_auto_20200921_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='object_type',
            field=models.CharField(choices=[('Agent', 'Agent'), ('Group', 'Group')], default='Activity', max_length=255),
            preserve_default=False,
        ),
    ]
