# Generated by Django 3.1.1 on 2020-10-03 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xapi', '0006_auto_20201001_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xapiactor',
            name='iri_type',
            field=models.CharField(choices=[('account', 'Account'), ('mbox', 'Email Address'), ('mbox_sha1sum', 'Email SHA1'), ('openid', 'OpenID')], max_length=255),
        ),
    ]
