# Generated by Django 3.1.1 on 2020-09-21 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xapi', '0006_activity_object_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name_plural': 'Activities'},
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(blank=True, help_text='Enter an Activity Type IRI if applicable. See some examples at https://registry.tincanapi.com/#home/activityTypes', max_length=1048, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='more_info',
            field=models.CharField(blank=True, help_text='Enter an IRI for more info.', max_length=1048, null=True),
        ),
    ]
