# Generated by Django 3.1.1 on 2020-10-04 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xapi', '0008_auto_20201004_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slackobjectfield',
            name='connector_id',
            field=models.CharField(blank=True, help_text='Use this field to group together multiple SlackObjectFields', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='slackverbfield',
            name='connector_id',
            field=models.CharField(blank=True, help_text='Use this field to group together multiple SlackVerbFields', max_length=50, null=True),
        ),
    ]
