# Generated by Django 3.1.1 on 2020-10-04 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xapi', '0009_auto_20201004_1737'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slackobjectfield',
            old_name='connector_id',
            new_name='field_group',
        ),
        migrations.RenameField(
            model_name='slackverbfield',
            old_name='connector_id',
            new_name='field_group',
        ),
    ]
