# Generated by Django 3.1.1 on 2020-10-06 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xapi', '0010_auto_20201004_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='xapiobject',
            name='id_field',
            field=models.CharField(default='event_id', max_length=20),
        ),
    ]
