# Generated by Django 3.1.1 on 2020-10-10 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xapi', '0011_xapiobject_id_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='lrsconfig',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
