# Generated by Django 3.1.1 on 2020-10-10 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xapi', '0012_lrsconfig_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='lrsconfig',
            name='display_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
