version: "3.4"

services:
  webapp: &webapp
    image: slack-to-xapi
    volumes:
      - ${PWD}/data/:/app/data/
      - ${PWD}/seed/:/app/seed/
    secrets:
      - source: dotenv
        target: /app/main/.env
    depends_on: 
      - rabbitmq
      - celery_worker

  celery_worker:
    <<: *webapp
    command: celery -A main worker --loglevel=info
    ports: []
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3.8.9-alpine
    ports:
      - "5672:5672"

  nginx:
    image: nginx
    volumes:
      - ${PWD}/nginx/:/etc/nginx/conf.d/
    ports:
      - "80:80"
    depends_on:
      - webapp
      - celery_worker

secrets:
  dotenv:
    file: .env