version: "3.4"

services:
  webapp: &webapp
    image: slack-to-xapi
    volumes:
      - ${PWD}/src/slack_events/:/app/slack_events/
      - ${PWD}/src/xapi/:/app/xapi/
      - ${PWD}/data/:/app/data/
    secrets:
      - source: dotenv
        target: /app/main/.env
    ports:
      - "8000:8000"
    depends_on: 
      - rabbitmq
      - celery_worker
  celery_worker:
    <<: *webapp
    command: celery -A main worker --loglevel=info
    ports: []
    depends_on:
      - rabbitmq
  rabbitmq:
    image: rabbitmq:3.8.9-alpine
  

secrets:
  dotenv:
    file: .env