version: "3.4"

services:
  webapp: &webapp
    image: slack-to-xapi
    volumes:
      - ${PWD}/data/:/app/data/
      - ${PWD}/seed/:/app/seed/
    secrets:
      - source: dotenv
        target: /app/main/.env

  nginx:
    image: nginx
    volumes:
      - ${PWD}/nginx/:/etc/nginx/conf.d/
    ports:
      - "80:80"
    depends_on:
      - webapp

secrets:
  dotenv:
    file: .env