# Generated by Django 3.1.1 on 2020-09-17 23:11

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('slack_events', '0003_slackevent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slackevent',
            old_name='token',
            new_name='channel',
        ),
        migrations.AddField(
            model_name='slackevent',
            name='attachments',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='slackevent',
            name='event_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='slackevent',
            name='event_subtype',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='slackevent',
            name='event_time',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='slackevent',
            name='event_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='slackevent',
            name='message_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='slackevent',
            name='payload',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='slackevent',
            name='team_id',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='slackevent',
            name='ts',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='slackevent',
            name='user',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
