# Generated by Django 3.1.1 on 2020-09-19 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slack_events', '0006_slackevent_mentioned_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='XApiConversion',
        ),
    ]
