# Generated by Django 3.1.1 on 2020-09-23 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slack_events', '0008_slackevent_has_mentions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slackevent',
            old_name='user',
            new_name='user_id',
        ),
    ]
