# Generated by Django 3.1.1 on 2020-09-30 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slack_events', '0010_slackevent_message_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slackevent',
            name='message_id',
        ),
    ]
