# Generated by Django 3.1.1 on 2020-10-04 12:34

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('slack_events', '0011_remove_slackevent_message_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='XApiStatement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', jsonfield.fields.JSONField()),
                ('delivered', models.BooleanField(default=False)),
                ('slack_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slack_event', to='slack_events.slackevent')),
            ],
        ),
    ]
