# Generated by Django 3.1.1 on 2020-10-04 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack_events', '0013_auto_20201004_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='slackevent',
            name='has_files',
            field=models.BooleanField(default=False),
        ),
    ]
