# Generated by Django 3.1.1 on 2020-10-06 22:49

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('slack_events', '0015_slackevent_permalink'),
    ]

    operations = [
        migrations.AddField(
            model_name='slackevent',
            name='file_ids',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
