# Generated by Django 3.1.1 on 2020-10-07 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack_events', '0016_slackevent_file_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slackevent',
            name='ts',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
