# Generated by Django 3.1.1 on 2020-10-07 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack_events', '0017_auto_20201007_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slackevent',
            name='ts',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
